sudo: required

language: bash

dist: xenial

services:
  - docker

script:
  - DOCKER_REPO=$DOCKER_USER
  - TAG="0.2"
  - CONT_NAME="ansible-control"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker build --build-arg -t $DOCKER_REPO/$CONT_NAME:latest .
  - docker images
  - docker tag $DOCKER_REPO/$CONT_NAME:latest $DOCKER_REPO/$CONT_NAME:$TAG
  - docker push $DOCKER_REPO/$CONT_NAME:$TAG
  - docker push $DOCKER_REPO/$CONT_NAME