trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub CultClassik'
    repository: 'cultclassik/ansible-boss'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest