trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub CultClassik'
    repository: 'ansible-boss'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest