trigger:
- master

pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageTag: '0.1'
  imageName: 'ansible-boss'
  dockerRepo: 'cultclassik'
  dockerHub: 'Docker Hub CultClassik'

steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(imageTag)
      latest
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      $(imageTag)
      latest